spring:
  application:
    name: store
  datasource:
    url: jdbc:postgresql://localhost:5433/store_api
    username: postgres
    password: matheus19dev
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update # I'm going to use Flyway for schema creation
